language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt 'pytest>=3.1.1' 'coveralls'"
script: "coverage run --source=firefly setup.py test"
after_success: coveralls
